### ISSUE TITLE
pg_rewrite is currently incompatible with PostgreSQL 16

### ISSUE THREAD

**Issue by markwort** [cybertec-postgresql/pg_rewrite#3]
There was some discussion around an issue introduced by some changes upstream, so I thought I'd document it someplace where it is publicly accessible.

This is the upstream change that breaks some of the functionality used by pg_rewrite:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=240e0dbacd

The fix should be quite similar to recent fixes in pg_squeeze.

**Comment by ahouska** [comment]
Fixed in the master branch, in particular the commit e79f4f82ddef929dc8c0934e4bd02a2f3a4d786f. A new branch for the new version to be created soon.
